private["_center","_dist","_randomDist","_height","_velocity","_sleep","_shell","_pos"];
if (!isServer) exitWith{};

_center = _this select 0;
_dist = _this select 1;
_randomDist = _this select 2;
_height = _this select 3;
_velocity = _this select 4;
_sleep = _this select 5;

_pos = [(_center select 0),(_center select 1)+1*(_dist+random(_randomDist)),_height];
_shell = "Sh_82mm_AMOS" createVehicle _pos;
_shell setVelocity [0,0,-_velocity];
sleep random _sleep;
_pos = [(_center select 0),(_center select 1)-1*(_dist+random(_randomDist)),_height];
_shell = "Sh_82mm_AMOS" createVehicle _pos;
_shell setVelocity [0,0,-_velocity];
sleep random _sleep;
_pos = [(_center select 0)+1*(_dist+random(_randomDist)),(_center select 1),_height];
_shell = "Sh_82mm_AMOS" createVehicle _pos;
_shell setVelocity [0,0,-_velocity];
sleep random _sleep;
_pos = [(_center select 0)-1*(_dist+random(_randomDist)),(_center select 1),_height];
_shell = "Sh_82mm_AMOS" createVehicle _pos;
_shell setVelocity [0,0,-_velocity];
sleep random _sleep;
_pos = [(_center select 0)+0.707*(_dist+random(_randomDist)),(_center select 1)+0.707*(_dist+random(_randomDist)),_height];
_shell = "Sh_82mm_AMOS" createVehicle _pos;
_shell setVelocity [0,0,-_velocity];
sleep random _sleep;
_pos = [(_center select 0)-0.707*(_dist+random(_randomDist)),(_center select 1)-0.707*(_dist+random(_randomDist)),_height];
_shell = "Sh_82mm_AMOS" createVehicle _pos;
_shell setVelocity [0,0,-_velocity];
sleep random _sleep;
_pos = [(_center select 0)-0.707*(_dist+random(_randomDist)),(_center select 1)+0.707*(_dist+random(_randomDist)),_height];
_shell = "Sh_82mm_AMOS" createVehicle _pos;
_shell setVelocity [0,0,-_velocity];
sleep random _sleep;
_pos = [(_center select 0)+0.707*(_dist+random(_randomDist)),(_center select 1)-0.707*(_dist+random(_randomDist)),_height];
_shell = "Sh_82mm_AMOS" createVehicle _pos;
_shell setVelocity [0,0,-_velocity];